<?php
/**
 * Fahim Software.
 *
 * @category  Fahim
 * @package   Fahim_ZipCodeValidator
 * @author    Fahim
 * @copyright Copyright (c) Fahim Software Private Limited (https://Fahim.com)
 * @license   https://store.Fahim.com/license.html
 */
?>
<span style="padding-left:250px;">
    <a href="<?= /* @noEscape */ $block->getViewFileUrl('Fahim_ZipCodeValidator::zipcodes.csv') ?>">
    <?= $block->escapeHtml(__("Download Example CSV")) ?></a>
</span>
